# Which linux distribution to use?
# FROM node:alpine 
FROM microsoft/nanoserver

# Copy all the file in the current directory into the app directory in the image
COPY . /app

# Current work directory
WORKDIR /app

# Command to execute the program
CMD node app.js
# 30:00