# Which linux distribution to use?
FROM node:alpine 

# Copy all the file in the current directory into the app directory in the image
COPY . /app

# Current work directory
WORKDIR /app

# Command to execute the program
CMD node app.js