# Which linux distribution to use?
# FROM node:alpine 
FROM node:alpine

# Copy all the file in the current directory into the app directory in the image
COPY . /app

# Current work directory
WORKDIR /app

RUN npm install
# Command to execute the program
CMD npm start
# 30:00